Limited retry with exponential backoff
netlogix/Netlogix.JobQueue.Scheduled pull request #7
Opened 2022-07-05 13:40 UTC by stephanschuler

2022-07-05 14:30 UTC, nlx-lars requested changes

2022-07-05 14:30 UTC, nlx-lars commented on Configuration/Settings.JobQueue.yaml.example
> +          # The backoff strategy determines the growth of the delay between consecutive tries.
This indentation looks wrong

2022-07-06 13:53 UTC, stephanschuler commented on Configuration/Settings.JobQueue.yaml.example
> +          # The backoff strategy determines the growth of the delay between consecutive tries.
Fixed.

2022-07-06 14:01 UTC, nlx-lars approved these changes

2022-07-06 14:03 UTC, merged